apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-gitops
  namespace: hello-gitops
  annotations:
    # alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{ "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing  
    kubernetes.io/ingress.class: alb
    

spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: hello-gitops
              servicePort: http

# spec:
#   rules:
#     - host: "argodemo.nzxt.com"
#       http:
#         paths:
#         - backend:
#           serviceName: ssl-redirect
#           servicePort: use-annotation
#           path: /*
#         - backend:
#           serviceName: hello-gitops
#           servicePort: 80
#           path:  /*
          # - path: /
          #   backend:
          #     serviceName: hello-gitops
          #     servicePort: 80