apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-gitops
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: hello-gitops
              servicePort: http